import control as ct
from iso15118.shared.messages.iso15118_2.datatypes import ProfileEntryDetails
from iso15118.shared.messages.datatypes import PVPMax
from iso15118.shared.messages.enums import UnitSymbol
import logging

logger = logging.getLogger(__name__)

"""beginning_of_profile_schedule: int= -1
Created on Fri Aug  9 00:37:56 2024
LQRchargeCurve

@author: ANAND
"""
# KS is btwn 1 and 20
def LQRChargeCurve(DepTime, EAmount, PMax, KS):
    # system matrices
    A=[0]*1
    B=[1]*1
    C=[1]*1
    D=[0]*1

    #define the initial condition
    x0= [0] * 1

    # define the time vector for simulation
    startTime=0
    endTime = round(DepTime/60)*60
    numberSamples = round(endTime/60)
    interval = (endTime - startTime) / numberSamples
    timeVector = [0] * numberSamples
    for i in range(0, numberSamples):
        timeVector[i] = startTime + i * interval

    # state weighting matrix
    Q=KS/1000

    # input weighting matrix
    R=KS*1000

    # system matrices

    sysStateSpace=ct.ss(A,B,C,D)
    xd = [EAmount]

    K, S, E = ct.lqr(sysStateSpace, Q, R)

    def multiply_matrices(matrix_a, matrix_b):
        # Check for valid dimensions for multiplication
        if len(matrix_a[0]) != len(matrix_b):
            raise ValueError("Number of columns in the first matrix must equal the number of rows in the second matrix.")

        # Initialize the result matrix with zeros
        result_matrix = [[0 for _ in range(len(matrix_b[0]))] for _ in range(len(matrix_a))]

        # Perform matrix multiplication
        for i in range(len(matrix_a)):
            for j in range(len(matrix_b[0])):
                for k in range(len(matrix_a[0])):
                    result_matrix[i][j] += matrix_a[i][k] * matrix_b[k][j]

        return result_matrix

    Acl=A-multiply_matrices(B,K)
    Bcl=-Acl
     
    # define the state-space model
    sysStateSpaceCl=ct.ss(Acl,Bcl,C,D)
     
    # define the input for closed-loop simulation
    inputCL=[[0] * numberSamples] 
    inputCL[0,:]=xd*([1] * numberSamples)
    logger.debug(f"Created input array with {EAmount=} and {numberSamples=}")
    returnSimulationCL = ct.forced_response(sysStateSpaceCl,
                                          timeVector,
                                          inputCL,
                                          x0)

    def transpose_nested_loops(matrix):
        # Initialize a new matrix with dimensions swapped
        transposed_matrix = [[0 for _ in range(len(matrix))] for _ in range(len(matrix[0]))]

        for i in range(len(matrix)):
            for j in range(len(matrix[0])):
                transposed_matrix[j][i] = matrix[i][j]
        return transposed_matrix
   

    # YC is state of charge of the vehicle (progress to eamount)
    # UC is power
    # TC is the timevector
    Yc = returnSimulationCL.states[0,:]
    Uc = transpose_nested_loops(-K*(returnSimulationCL.states[0,:]-inputCL)) #also complex, might need a nested loop again
    Tc = returnSimulationCL.time

    return Yc, Uc, Tc


'''
    formatCurveData takes the output of the LQR ChargeCurve below, and formats
    it into a JSON string that will be accepted by Node-RED's `chart`
    module.

    @author Katie
'''
def formatCurveData(profile_entry_list):
    # Node-RED expects watts & miliseconds
    yc_curve = [{"x": float(ped.start), "y": float(ped.max_power.value)} for ped in profile_entry_list]
    return {
      "series": ["A"],
      "data": [yc_curve],
      "labels": ["r1"]
    }


'''
    generate_new_schedule is used in `evcc/simulator.py`'s `process_sa_schedules_v2` to
    create a profile_entry list from both the existing `secc_schedule` and a schedule
    generated by the above LQR Charging Optimizer 

    @author Katie
'''
def generate_new_schedule(secc_schedule, uc, tc, departure_time, time_elapsed):
    # time_offset = 24 * # max enteries is 24, so refresh every <24 -ish seconds?
    # Define some helper functions...
    # Evenly sample from the `curve_schedule`< up to the end timestamp
    def sample_schedule(schedule):

        sliced_array = [x for x in schedule if (time_elapsed <= x[1])]
        return sliced_array[0:23]

    # Generates a ProfileEntryDetails obj for the final schedule
    def make_entry(val, timestamp, next_ts):
        # First, convert kWh to kW
        time_delta = (float(next_ts) - float(timestamp)) / 3600
        watts = (1000 * val) / time_delta
        # Then, create the ProfileEntryDetails...
        return  ProfileEntryDetails(
            start=int(timestamp),
            max_power=PVPMax(
                multiplier=0,
                value=watts, # Convert miliwattsHours to WattHours
                unit=UnitSymbol.WATT
            ),
            max_phases_in_use = None
        )

    def convert_tuple_schedule(curve_arr):
        schedule_arr = []
        for i in range(0, len(curve_arr) - 2):
            schedule_arr.append(make_entry(curve_arr[i][0], curve_arr[i][1], curve_arr[i+1][1]))
        logger.debug('Done converting tuple schedule')
        if (len(schedule_arr)):
            schedule_arr.pop(-1)

        return (schedule_arr)

    curve_schedule = [(x[0],y) for x, y, in zip(uc, tc)] # UC is in kWh, not kW
    # We get 24 from ISO 15118-2, Table 71.  This is the max number of profile enteries.
    # For some reason, EVerest only accepts 23... Investigate later
    curve_schedule = sample_schedule(curve_schedule)

    if (len(curve_schedule) <= 2): # Check to see if we're done...
        logger.debug("Done with profile, defaulting to SECC Schedule")
        return secc_schedule

    curve_schedule = convert_tuple_schedule(curve_schedule)
    logger.debug(f"Returning a curve schedule of: {curve_schedule}")

    return curve_schedule

def generate_dummy_schedule():
    watt_vals = [3330, 2300, 1300, 500]
    temp = []

    for i in range(len(watt_vals)):
        temp.append(ProfileEntryDetails(
            start=10 * i,
            max_power=PVPMax(
                multiplier=0,
                value=watt_vals[i],
                unit=UnitSymbol.WATT
            ),
            max_phases_in_use = None
            )
        )
    logger.debug(f'Dummy schedule: {temp}')
    return temp
